## Erick J. Pineda Amézquita      - - - - - 17012140
#### Statistical Learning II
#### Maldición de la dimensionalidad y características polinomiales


En este notebook se va demostrar que mientras mas variables se tenga en un modelo, mas complejo será el problema a resolver. Comúnmente se cree que debería utilizarce la mayor cantidad de datos disponibles, todas las columnas que tenga la tabla de entrada, sin embargo, esto puede causar problemas de rendimiento computacional o crear un modelo deficiente, por tal razón es neceario aplicar otras técnicas que reduzcan el espacio de los datos, por ejemplo, aplicar feature engineering, PCA, T-SNE, o regularización.

In [1]:
## se importan librerias
import numpy as np
from sklearn.preprocessing import PolynomialFeatures


### Tomar en cuenta el funcionamiento del paquete "PolynomialFeatures":
Según la documentación:

"PolynomialFeatures generates a new matrix with all polynomial combinations of features with given degree.

Like [a] will be converted into [1,a,a^2] for degree 2.

You can visualize input being transformed into matrix generated by PolynomialFeatures."



In [2]:
from sklearn.preprocessing import PolynomialFeatures
a = np.array([1,2,3,4,5])
a = a[:,np.newaxis]
poly = PolynomialFeatures(degree=2)
a_poly = poly.fit_transform(a)
print(a_poly)


[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


### Comenzado la demostración: Creacion de variables o dimensiones

Definición de variables unidimensionales, bidimensionales y tridimensionales y de grado alto mayor a 10

In [3]:
feature10x1 = np.random.rand(10,1)
feature10x2 = np.random.rand(10,2)
feature10x3 = np.random.rand(10,3)
feature10x15 = np.random.rand(10,15)
feature10x30 = np.random.rand(10,30)

print(feature10x1.shape)
print(feature10x2.shape)
print(feature10x3.shape)
print(feature10x30.shape)
print(feature10x15.shape)

(10, 1)
(10, 2)
(10, 3)
(10, 30)
(10, 15)


### Creación de modelos polinomiales de grado 1, 2, 3, 15 y 50

In [4]:
polinomioG1=PolynomialFeatures(1)
polinomioG2=PolynomialFeatures(2)
polinomioG3=PolynomialFeatures(3)
polinomioG15=PolynomialFeatures(15)
polinomioG50=PolynomialFeatures(50)

### Entrenamiento de los modelos en base a las dimensiones de entrada

Grado 1 con 1 variable, genera 2 columnas utilizando un polinomio de grado 1.

In [5]:
resultado= polinomioG1.fit_transform(feature10x1)
print(feature10x1)
print(resultado)
print(resultado.shape)


[[0.95594937]
 [0.89936641]
 [0.3571963 ]
 [0.48087234]
 [0.53625093]
 [0.486834  ]
 [0.06814783]
 [0.02114872]
 [0.57219848]
 [0.29484912]]
[[1.         0.95594937]
 [1.         0.89936641]
 [1.         0.3571963 ]
 [1.         0.48087234]
 [1.         0.53625093]
 [1.         0.486834  ]
 [1.         0.06814783]
 [1.         0.02114872]
 [1.         0.57219848]
 [1.         0.29484912]]
(10, 2)


Grado 2 con 2 variable, observar que genera 6 nuevas variables.

In [6]:
print(feature10x2)
resultado= polinomioG2.fit_transform(feature10x2)
resultado.shape

[[0.57144631 0.84606712]
 [0.95387643 0.05972299]
 [0.72136054 0.98868388]
 [0.35361143 0.86874713]
 [0.40345864 0.17776566]
 [0.82409401 0.91798414]
 [0.90241466 0.38858923]
 [0.22412895 0.00893974]
 [0.6987013  0.52127937]
 [0.47954399 0.02592959]]


(10, 6)

Grado 3 con 3 variables, observar que a partir de 3 columnas está generando 20 nuevas variables.

In [7]:
print(feature10x3)
resultado= polinomioG3.fit_transform(feature10x3)
resultado.shape

[[0.19216334 0.35724382 0.38327506]
 [0.3380894  0.84698775 0.19383728]
 [0.45111214 0.03664411 0.17190759]
 [0.19081053 0.31425631 0.22885773]
 [0.24695816 0.71758593 0.58905331]
 [0.56987278 0.12874659 0.41222561]
 [0.20604366 0.86128674 0.70723934]
 [0.63024097 0.48014603 0.20195555]
 [0.23171932 0.94196905 0.43178906]
 [0.08630802 0.56183092 0.93769725]]


(10, 20)

Grado 15 con 3 variables, observar que a partir de 3 columnas está generando 816 nuevas variables si se utiliza grado 15.

In [8]:
print(feature10x3)
resultado= polinomioG15.fit_transform(feature10x3)
resultado.shape


[[0.19216334 0.35724382 0.38327506]
 [0.3380894  0.84698775 0.19383728]
 [0.45111214 0.03664411 0.17190759]
 [0.19081053 0.31425631 0.22885773]
 [0.24695816 0.71758593 0.58905331]
 [0.56987278 0.12874659 0.41222561]
 [0.20604366 0.86128674 0.70723934]
 [0.63024097 0.48014603 0.20195555]
 [0.23171932 0.94196905 0.43178906]
 [0.08630802 0.56183092 0.93769725]]


(10, 816)

Grado 50 con 3 variables, observar que a partir de 3 columnas está generando 23,426 nuevas variables si se utiliza grado 50.

In [9]:
print(feature10x3)
resultado= polinomioG50.fit_transform(feature10x3)
resultado.shape


[[0.19216334 0.35724382 0.38327506]
 [0.3380894  0.84698775 0.19383728]
 [0.45111214 0.03664411 0.17190759]
 [0.19081053 0.31425631 0.22885773]
 [0.24695816 0.71758593 0.58905331]
 [0.56987278 0.12874659 0.41222561]
 [0.20604366 0.86128674 0.70723934]
 [0.63024097 0.48014603 0.20195555]
 [0.23171932 0.94196905 0.43178906]
 [0.08630802 0.56183092 0.93769725]]


(10, 23426)

## Conclusiones:
Mientras mas variables se tengan, el polinomio se vuelve mas complejo. Esto representa un claro problemo de Overfitting, por lo que el modelo puede fallar cuando se ingresen valores desconocidos o fuera del rango de los datos de entrenamiento. 
El problema también reside en el procesamiento, mientras mas columnas o variables tengamos, el costo de procesamiento será mas elevado al mismo tiempo que se sacrifica la precisión del modelo. 

Para solucionar este tipo de problemas se puede utilizar regularización, feature engineering, analisis de varianzas ya sea por homocedasticidad o heterocedasticidad, correlación entre variables independientes, selección de variables en base algún criterio no aleatorio. 